# Build stage
FROM rust:1.88-slim as builder
WORKDIR /app
COPY backend .

RUN apt-get update && apt-get install -y \
  libpq-dev \
  libpq5 \
  && rm -rf /var/lib/apt/lists/*

RUN cargo build --release

# Production stage
FROM debian:stable-slim
RUN apt-get update && apt-get install -y \
  libpq-dev \
  libpq5 \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/local/bin
COPY --from=builder /app/target/release/share_count .
CMD ["./share_count"]
