name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_backend:
    uses: ./.github/workflows/build_backend.yml
    secrets: inherit
  build_frontend:
    uses: ./.github/workflows/build_frontend.yml
    secrets: inherit

