name: Backend

on:
  workflow_call:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run postgresql
      run: docker compose -f ../docker/db/docker-compose-test.yml up --detach
    - name: Run Tests
      run: sh launch_test.sh
    - name: Shutdown postgresql
      run: docker compose -f ../docker/db/docker-compose-test.yml down
    - uses: actions/upload-artifact@v4
      with:
        path: ./backend/target/release/share_count

