name: Frontend

on:
  workflow_call:
    inputs:
      upload:
        default: false
        description: "Upload"
        required: true
        type: boolean

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
    - name: Prepare wasm
      run: |
        chmod +x scripts/setup.sh
        ./scripts/setup.sh
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: LS
      run: ls -a
    - name: Upload artifact
      if: ${{ inputs.upload }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: './frontend/build'