name: Frontend

on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
    - name: Open Web Client Directory
      run: |
        ls -la
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build