name: Builder

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_backend:
    uses: ./.github/workflows/build_backend.yml
    secrets: inherit
  build_frontend:
    uses: ./.github/workflows/build_frontend.yml
    secrets: inherit
    with:
      upload: false
  build_android:
    uses: ./.github/workflows/build_android.yml
    secrets: inherit
